receivers:
  filelog:
    include:
      - /var/log/clickhouse-server/clickhouse-server.log
      - /var/log/clickhouse-server/clickhouse-server.err.log
    start_at: beginning
  
  prometheus:
    config:
      scrape_configs:
        - job_name: "demo"
          scrape_interval: 5s
          static_configs:
            - targets: ["host.docker.internal:8080"]
    
  hostmetrics:
    collection_interval: 5s
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
      network:
      load:

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  filter/only_summary:
    metrics:
      metric:
          - 'type != METRIC_DATA_TYPE_SUMMARY'
      datapoint:
          - 'metric.type != METRIC_DATA_TYPE_SUMMARY'
  batch:
    timeout: 30s
    send_batch_size: 10

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8889" 
  otlphttp:
    # endpoint: "https://otel.kloudmate.dev:4318"
    endpoint: "http://host.docker.internal:4318"
    headers: 
      Authorization: sk_Ovy8MflXEvH9KajY8lwUxyhW
    timeout: 5s

service:
  pipelines:
    logs:
      receivers: [otlp, filelog]
      processors: [batch]
      exporters: [otlphttp]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      exporters: [otlphttp]
    traces:
      receivers: [otlp]    
      processors: [batch] 
      exporters: [otlphttp]