receivers:
  filelog:
    include:
      - /var/log/*/*.log*
    start_at: beginning
    include_file_path: true

  hostmetrics:
    collection_interval: 5s
    scrapers:
      memory:
      system:
      cpu:
      disk:

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318


processors:
  # Adds service.name and other resource-level metadata
  resource:
    attributes:
      - action: upsert
        key: service.name
        value: test_service   # change this per service / env

  # Optional: useful if you later want dynamic parsing
  transform/set_service_from_file:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          # Example: override service.name if needed (disabled by default)
          # - set(resource.attributes["service.name"], attributes["log.file.path"])
          #   where attributes["log.file.path"] != nil

  batch:
    timeout: 10s


exporters:
  otlphttp:
    # endpoint: "https://otel.kloudmate.dev:4318"
    endpoint: "http://host.docker.internal:4318"
    headers:
      Authorization: sk_Ovy8MflXEvH9KajY8lwUxyhW
    timeout: 10s

  debug:
    verbosity: detailed

  prometheus:
    endpoint: "0.0.0.0:8889"


service:
  pipelines:
    # logs:
    #   receivers: [otlp, filelog]
    #   processors: [resource, batch]
    #   exporters: [otlphttp]

    metrics:
      receivers: [otlp, hostmetrics]
      processors: [resource, batch]
      exporters: [otlphttp, debug]

    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlphttp]